import type { StrategyId } from '../../../../packages/shared/src';

export const FINAL_SINGLE_FILL_GRACE_MS = 60_000;
export const CLASSIC_ENTRY_STRATEGY: StrategyId = 'UPDOWN_DUAL_ENTRY';
export const EXPERIMENT_STRATEGY: StrategyId = 'UPDOWN_NEXT_ROUND_50_49_STOP_ON_SINGLE';
export const PRICE_CAP_HEDGE_REASONS = new Set(['HEDGE_ASK_ABOVE_CAP', 'HEDGE_PAIR_COST_ABOVE_CAP', 'EARLY_HEDGE_PAIR_COST_ABOVE_CAP', 'EMERGENCY_HEDGE_PAIR_COST_ABOVE_CAP']);
export const BENIGN_HEDGE_REASONS = new Set(['NO_MATERIAL_SINGLE_FILL_EXPOSURE', 'NOT_IN_HEDGE_WINDOW', 'HEDGE_TOO_CLOSE_TO_EXPIRY']);
