import type { StrategyRule } from '../../shared/src';

export const STRATEGY_RULES: StrategyRule[] = [
  {
    id: 'UPDOWN_DUAL_ENTRY',
    title: 'Up/Down Dual Entry',
    allocationPct: 1,
    summary: 'Pre-commit YES and NO liquidity with fixed profile limit pricing and fixed profile sizing before the next round starts.',
    entryRules: [
      'Round must be inside the T-30s decision window before start.',
      'Score and volatility gates may be bypassed; execution gates such as cooldown, tradable books, duplicate orders, and balance checks still apply.',
      'YES and NO books must be live, fresh, and buyable for the configured limit to be valid.',
      'Extreme imbalance in YES vs NO bid queue at the entry limit is blocked; mild imbalance is only diagnostic.',
      'Shares come from the active market profile.',
      'No duplicate local or Polymarket open order may exist for the same round/token.',
      'Live entry orders are posted as GTC limit orders; post-start risk is handled by the profit-exit and hedge rules.',
    ],
    exitRules: [
      'If both sides fill, hold paired exposure through settlement.',
      'If only one side fills and its live bid becomes profitable, a separate profit-exit rule may cancel the missing-side buy and sell the filled side with a capped FAK limit.',
      'If the filled side is losing but still inside the configured loss budget, a separate loss-exit rule may cancel the missing-side buy and sell the filled side with a capped FAK limit.',
      'If only one side fills, a separate last-window hedge rule may buy the missing side with a capped aggressive FAK limit order.',
      'Final single-sided fills use adaptive cooldown: short for ordinary/price-cap misses, longer for execution failures, and escalating for repeats.',
      'Outside the configured single-fill hedge window, the bot does not add, sell, or rebalance after the round starts.',
      'Execution rejects all SELL intents and rejects normal entry intents after round start; hedge intents use the separate capped hedge gate.',
    ],
  },
  {
    id: 'UPDOWN_SINGLE_FILL_HEDGE',
    title: 'Up/Down Single-Fill Stop-Loss Hedge',
    allocationPct: 0,
    summary: 'Near the end of an active round, cancel stale missing-side entry orders and buy the missing side only if the active profile hedge caps allow it.',
    entryRules: [
      'Round must already be running and inside SINGLE_FILL_EARLY_HEDGE_WINDOW_SECONDS, but not inside SINGLE_FILL_HEDGE_MIN_SECONDS_TO_END.',
      'Exactly one side must have more BUY fills than the other side by at least the minimum order size.',
      'The missing-side orderbook must be live, fresh, and have bestAsk <= SINGLE_FILL_HEDGE_MAX_PRICE.',
      'Outside the final hedge window, dominant-side average fill price plus hedge limit price must be <= SINGLE_FILL_EARLY_HEDGE_MAX_PAIR_COST.',
      'Inside the final hedge window, dominant-side average fill price plus hedge limit price must be <= SINGLE_FILL_HEDGE_MAX_PAIR_COST.',
      'The hedge is posted as a capped FAK BUY LIMIT order, not an uncapped market order.',
    ],
    exitRules: [
      'No SELL hedge is generated.',
      'If the cap is exceeded, the bot leaves the single-sided exposure open through settlement.',
    ],
  },
  {
    id: 'UPDOWN_NEXT_ROUND_50_49_STOP_ON_SINGLE',
    title: 'Up/Down Experimental Next-Round 50/49',
    allocationPct: 0,
    summary: 'Experimental profile that continuously posts fixed next-round UP/DOWN entry limits and stops after a final single-sided fill.',
    entryRules: [
      'Only runs when ACTIVE_STRATEGY_PROFILE=experiment_next_round.',
      'For each next round before start, post UP/YES BUY LIMIT at EXPERIMENT_NEXT_ROUND_UP_LIMIT_PRICE.',
      'For each next round before start, post DOWN/NO BUY LIMIT at EXPERIMENT_NEXT_ROUND_DOWN_LIMIT_PRICE.',
      'Shares per side come from EXPERIMENT_NEXT_ROUND_SHARES_PER_SIDE.',
      'After a final single-sided experimental fill, the experimental profile stops generating new entries.',
    ],
    exitRules: [
      'No profit exit is generated for experimental orders.',
      'No single-fill hedge is generated for experimental orders.',
      'No SELL intent is generated by this profile.',
      'Switching back to classic leaves experimental orders out of classic exit handling.',
    ],
  },
  {
    id: 'UPDOWN_SINGLE_FILL_PROFIT_EXIT',
    title: 'Up/Down Single-Fill Profit Exit',
    allocationPct: 0,
    summary: 'When a single filled side can be sold for a configured profit, cancel the stale missing-side buy order and exit the filled side using a capped FAK sell limit.',
    entryRules: [
      'Round must already be running and inside the configured profit-exit window.',
      'Exactly one side must have net BUY exposure by at least the minimum order size.',
      'The filled-side orderbook must be live, fresh under SINGLE_FILL_PROFIT_EXIT_MAX_ORDERBOOK_AGE_MS, and have bestBid >= SINGLE_FILL_PROFIT_EXIT_MIN_PRICE.',
      'The capped sell limit must realize at least SINGLE_FILL_PROFIT_EXIT_MIN_PNL_USD.',
      'The exit is posted as a FAK SELL LIMIT, not an uncapped market order.',
    ],
    exitRules: [
      'The missing-side open BUY order is cancelled before the sell attempt.',
      'If the bid moves below the configured floor after cancellation, the sell is skipped and the single exposure remains managed by the hedge rule.',
    ],
  },
  {
    id: 'UPDOWN_SINGLE_FILL_LOSS_EXIT',
    title: 'Up/Down Single-Fill Loss Exit',
    allocationPct: 0,
    summary: 'When a single filled side is losing but still inside the configured loss budget, cancel the stale missing-side buy order and exit the filled side using a capped FAK sell limit.',
    entryRules: [
      'Round must already be running and inside the configured loss-exit window.',
      'Exactly one side must have net BUY exposure by at least the minimum order size.',
      'The filled-side orderbook must be live, fresh under SINGLE_FILL_LOSS_EXIT_MAX_ORDERBOOK_AGE_MS, and have bestBid >= SINGLE_FILL_LOSS_EXIT_MIN_BID.',
      'The capped sell limit must realize a loss no larger than SINGLE_FILL_LOSS_EXIT_MAX_LOSS_USD.',
      'The exit is posted as a FAK SELL LIMIT, not an uncapped market order.',
    ],
    exitRules: [
      'The missing-side open BUY order is cancelled before the sell attempt.',
      'If the bid is below the configured floor or the loss is already above budget, the sell is skipped and the single exposure remains managed by the hedge rule.',
    ],
  },
];
